---
- hosts: localhost
  connection: local

  vars:
    work_folder: "ssl"
    crt_list:
      - file: "server"
        name: "admin"
        alt_names: >- 
          IP.1:127.0.0.1,
          DNS.1:localhost,
          DNS.2:opensearch-min,
          DNS.3:opensearch-dashboards-min,
          DNS.4:*
    
  tasks:
  - name: make folders
    file:
      dest: "{{ item }}"
      state: directory
    with_items:
    - "{{ work_folder }}/crt"
    - "{{ work_folder }}/csr"
    - "{{ work_folder }}/key"


  - name: gen client csr
    shell: >-
      openssl req -new
      -newkey rsa:4096
      -sha256
      -nodes
      -subj       "/CN={{ item.name }}"
      -addext     "subjectAltName = {{ item.alt_names }}"
      -addext     "extendedKeyUsage = serverAuth, clientAuth"
      -keyout     key/{{ item.file }}.key
      -out        csr/{{ item.file }}.csr
    args:
      creates: csr/{{ item.file }}.csr
      chdir: "{{ work_folder }}"
    with_items: "{{ crt_list }}"
    loop_control:
      label: "{{ item.file }}"

  - name: sign client csr
    shell: >-
      openssl x509 
      -req -days 365 
      -copy_extensions copyall
      -signkey key/{{ item.file }}.key
      -in      csr/{{ item.file }}.csr
      -out     crt/{{ item.file }}.crt
    args:
      creates: crt/{{ item.file }}.crt
      chdir: "{{ work_folder }}"
    with_items: "{{ crt_list }}"
    loop_control:
      label: "{{ item.file }}"

  - name: fix permissions
    file:
      path: "{{ work_folder }}/key/{{ item.file }}.key"
      mode: "0644"
    with_items: "{{ crt_list }}"
    loop_control:
      label: "{{ item.file }}"