version: '3'
services:
  # OPENSEARCH
  opensearch-min: 
    image: opensearchproject/opensearch:$OS_VERSION
    container_name: opensearch-min
    hostname:       opensearch-min
    environment:
      cluster.name: opensearch-cluster
      node.name:    opensearch-min
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      OPENSEARCH_JAVA_OPTS:  '-Xms1024m -Xmx1024m'
      COMPATIBILITY_OVERRIDE_MAIN_RESPONSE_VERSION: 'true'

    ulimits:
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    volumes:
      - type: volume 
        source: opensearch-min
        target: /usr/share/opensearch/data
        read_only: false
    ports:    ['9200:9200', '9600:9600']
    networks: ['opensearch-min']

  # DASHBOARDS
  opensearch-dashboards-min:
    image: opensearchproject/opensearch-dashboards:$OS_VERSION
    container_name: opensearch-dashboards-min
    hostname:       opensearch-dashboards-min
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-min:9200"]'
    ports:    ['5601:5601']
    networks: ['opensearch-min']

  # AUDITBEAT
  auditbeat:
    image: docker.elastic.co/beats/auditbeat-oss:7.10.2
    container_name: auditbeat
    hostname:       auditbeat
    command: ["--strict.perms=false"]
    user: root
    pid:  host
    cap_add:
      - AUDIT_CONTROL
      - AUDIT_READ
    volumes:
      - type:    bind
        source: ./configs/auditbeat/auditbeat.yml
        target:  /usr/share/auditbeat/auditbeat.yml
        read_only: true
      - type:    bind
        source: ./configs/auditbeat/auditd-rules.txt
        target:  /usr/share/auditbeat/auditd-rules.txt
        read_only: true
    networks: ['opensearch-min']

  # FILEBEAT
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.10.2
    container_name: filebeat
    hostname:       filebeat
    command: ["--strict.perms=false"]
    user: root
    volumes:
      - type:    bind
        source: ./configs/filebeat/filebeat.yml
        target:  /usr/share/filebeat/filebeat.yml
        read_only: true
      - type:    bind
        source:  /var/log
        target:  /mnt/var/log
        read_only: true
    networks: ['opensearch-min']

  # VECTOR
  vector:
    image: timberio/vector:0.26.0-alpine
    container_name: vector
    hostname:       vector
    environment:
      VECTOR_LOG: info
    volumes:
      - type: bind
        source:   ./configs/vector/vector.yml
        target:    /etc/vector/vector.yml
        read_only: true
    command:  ['-c', '/etc/vector/vector.yml']
    networks: ['opensearch-min']
    

volumes:
  opensearch-min:
    name: opensearch-min

networks:
  opensearch-min:
    name: opensearch-min