version: '3'
services:
  # OPENSEARCH
  opensearch-min: 
    image: opensearchproject/opensearch:$OS_VERSION
    container_name: opensearch-min
    hostname:       opensearch-min
    environment:
      cluster.name: opensearch-cluster
      node.name:    opensearch-min
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      OPENSEARCH_JAVA_OPTS:  '-Xms1024m -Xmx1024m'
      COMPATIBILITY_OVERRIDE_MAIN_RESPONSE_VERSION: 'true'

    ulimits:
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    volumes:
      - type: volume 
        source: opensearch-min
        target: /usr/share/opensearch/data
        read_only: false
    networks: ['opensearch-min']
    ports:    ['9200:9200', '9600:9600']
    restart: always

  # DASHBOARDS
  opensearch-dashboards-min:
    image: opensearchproject/opensearch-dashboards:$OS_VERSION
    container_name: opensearch-dashboards-min
    hostname:       opensearch-dashboards-min
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-min:9200"]'
    depends_on: ['opensearch-min']
    networks:   ['opensearch-min']
    ports:      ['5601:5601']
    restart: always

  # TELEGRAF
  telegraf:
    image: telegraf:1.23.4-alpine
    container_name: telegraf
    hostname:       telegraf
    volumes:
      - type: bind
        source: ./configs/telegraf/telegraf.conf
        target:  /etc/telegraf/telegraf.conf
        read_only: true
    depends_on: ['opensearch-min']
    networks:   ['opensearch-min']
    ports:      ['8125:8125', '9273:9273']
    restart: always

  # PROMETHEUS
  prometheus:
    image:          prom/prometheus:v2.42.0
    container_name: prometheus
    hostname:       prometheus
    volumes:
      - type: bind
        source: ./configs/prometheus
        target:  /etc/prometheus/
        read_only: true
    depends_on: ['telegraf']
    networks:   ['opensearch-min']
    ports:      ['9090:9090']
    restart: always

  # GRAFANA
  grafana:
    image:          grafana/grafana:9.3.6
    container_name: grafana
    hostname:       grafana
    volumes:
      - type:      volume
        source:    grafana-data-vol
        target:    /var/lib/grafana
        read_only: false
    depends_on: ['prometheus']
    networks:   ['opensearch-min']
    ports:      ['3000:3000']
    restart: always

volumes:
  opensearch-min:
    name: opensearch-min
  grafana-data-vol:
    name: grafana-data-vol

networks:
  opensearch-min:
    name: opensearch-min
  