auditbeat.modules:
- module: auditd
  resolve_ids: true
  failure_mode: silent
  rate_limit: 0
  include_raw_message: false
  include_warnings: false
  audit_rule_files: /usr/share/auditbeat/auditd-rules.txt

max_procs: 2

setup.kibana:
  enable: false

output.elasticsearch:
  enabled: true
  hosts: ["https://osc:9200"]
  username: admin
  password: a12345678
  ssl.verification_mode: certificate
  ssl.certificate_authorities:
  - /usr/share/auditbeat/ssl/crt/server.crt

output.logstash:
  enabled: false

output.console:
  enabled: false
  pretty:  true

processors:
  - add_host_metadata: ~

monitoring.enabled: false

logging:
  level: info
  to_stderr: true
  json: false
  metrics.enabled: false
